services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - hackingly-net
    volumes:
      - mongo_data:/data/db

  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/mydb 
    networks:
      - hackingly-net

networks:
  hackingly-net:

volumes:
  mongo_data:

